version: '3'
services:
  gamesbox:
    image: gamesbox:latest
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - IGDB_CLIENT=
      - IGDB_SECRET=
      - DB_USER=root
      - DB_PASSWORD=password
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=gamesboxuser
      - MYSQL_DATABASE=gamesbox
      - MYSQL_ROOT_PASSWORD=password


